<template><div><div class="language-python line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre  class="shiki github-dark vp-code" style="background-color:#24292e;color:#e1e4e8 language-python"><code><span class="line"><span class="line"><span style="color:#F97583">    async</span><span style="color:#F97583"> def</span><span style="color:#B392F0"> on_message</span><span style="color:#E1E4E8">(self, message: Dict[</span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">, Any]) -> </span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">:</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">        """当收到消息时调用"""</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#79B8FF"> None</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    async</span><span style="color:#F97583"> def</span><span style="color:#B392F0"> on_file_upload</span><span style="color:#E1E4E8">(self, file_path: </span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">):</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">        """当文件被上传时调用"""</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        pass</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    def</span><span style="color:#B392F0"> get_commands</span><span style="color:#E1E4E8">(self) -> List[Dict[</span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">, </span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">]]:</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">        """获取插件支持的命令列表"""</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#E1E4E8"> []</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    async</span><span style="color:#F97583"> def</span><span style="color:#B392F0"> handle_command</span><span style="color:#E1E4E8">(self, command: </span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">, args: Dict[</span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">, Any]) -> </span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">:</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">        """处理插件命令"""</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#F97583"> f</span><span style="color:#9ECBFF">"Command '</span><span style="color:#79B8FF">{</span><span style="color:#E1E4E8">command</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF">' not implemented for </span><span style="color:#79B8FF">{self</span><span style="color:#E1E4E8">.name</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF">"</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    def</span><span style="color:#B392F0"> get_help</span><span style="color:#E1E4E8">(self) -> </span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">:</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">        """获取插件帮助信息"""</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        commands </span><span style="color:#F97583">=</span><span style="color:#79B8FF"> self</span><span style="color:#E1E4E8">.get_commands()</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        if</span><span style="color:#F97583"> not</span><span style="color:#E1E4E8"> commands:</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">            return</span><span style="color:#F97583"> f</span><span style="color:#9ECBFF">"</span><span style="color:#79B8FF">{self</span><span style="color:#E1E4E8">.name</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF"> v</span><span style="color:#79B8FF">{self</span><span style="color:#E1E4E8">.version</span><span style="color:#79B8FF">}\n{self</span><span style="color:#E1E4E8">.description</span><span style="color:#79B8FF">}\n</span><span style="color:#9ECBFF">该插件没有可用的命令。"</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        </span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        help_text </span><span style="color:#F97583">=</span><span style="color:#F97583"> f</span><span style="color:#9ECBFF">"</span><span style="color:#79B8FF">{self</span><span style="color:#E1E4E8">.name</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF"> v</span><span style="color:#79B8FF">{self</span><span style="color:#E1E4E8">.version</span><span style="color:#79B8FF">}\n{self</span><span style="color:#E1E4E8">.description</span><span style="color:#79B8FF">}\n\n</span><span style="color:#9ECBFF">可用命令:</span><span style="color:#79B8FF">\n</span><span style="color:#9ECBFF">"</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        for</span><span style="color:#E1E4E8"> cmd </span><span style="color:#F97583">in</span><span style="color:#E1E4E8"> commands:</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">            help_text </span><span style="color:#F97583">+=</span><span style="color:#F97583"> f</span><span style="color:#9ECBFF">"/</span><span style="color:#79B8FF">{</span><span style="color:#E1E4E8">cmd[</span><span style="color:#9ECBFF">'name'</span><span style="color:#E1E4E8">]</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF"> - </span><span style="color:#79B8FF">{</span><span style="color:#E1E4E8">cmd[</span><span style="color:#9ECBFF">'description'</span><span style="color:#E1E4E8">]</span><span style="color:#79B8FF">}\n</span><span style="color:#9ECBFF">"</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#E1E4E8"> help_text</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


