<template><div><div class="language-python line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre  class="shiki github-dark vp-code" style="background-color:#24292e;color:#e1e4e8 language-python"><code><span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#F97583">async</span><span style="color:#F97583"> def</span><span style="color:#B392F0"> process_plugin_message</span><span style="color:#E1E4E8">(message):</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">    """处理插件消息"""</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    try</span><span style="color:#E1E4E8">:</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        plugin_result </span><span style="color:#F97583">=</span><span style="color:#F97583"> await</span><span style="color:#E1E4E8"> plugin_manager.handle_message(message)</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#E1E4E8"> plugin_result</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    except</span><span style="color:#79B8FF"> Exception</span><span style="color:#F97583"> as</span><span style="color:#E1E4E8"> e:</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        logger.error(</span><span style="color:#F97583">f</span><span style="color:#9ECBFF">"Error in process_plugin_message: </span><span style="color:#79B8FF">{str</span><span style="color:#E1E4E8">(e)</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF">"</span><span style="color:#E1E4E8">)</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#79B8FF"> None</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#F97583">async</span><span style="color:#F97583"> def</span><span style="color:#B392F0"> process_plugin_command</span><span style="color:#E1E4E8">(user_input, message):</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">    """处理插件命令"""</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    try</span><span style="color:#E1E4E8">:</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        for</span><span style="color:#E1E4E8"> plugin </span><span style="color:#F97583">in</span><span style="color:#E1E4E8"> plugin_manager.enabled_plugins.values():</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">            command_response </span><span style="color:#F97583">=</span><span style="color:#F97583"> await</span><span style="color:#E1E4E8"> plugin.handle_command(user_input, message)</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">            if</span><span style="color:#E1E4E8"> command_response:</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">                return</span><span style="color:#E1E4E8"> command_response</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#79B8FF"> None</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    except</span><span style="color:#79B8FF"> Exception</span><span style="color:#F97583"> as</span><span style="color:#E1E4E8"> e:</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        logger.error(</span><span style="color:#F97583">f</span><span style="color:#9ECBFF">"Error in process_plugin_command: </span><span style="color:#79B8FF">{str</span><span style="color:#E1E4E8">(e)</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF">"</span><span style="color:#E1E4E8">)</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#79B8FF"> None</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#F97583">async</span><span style="color:#F97583"> def</span><span style="color:#B392F0"> upload_file_for_plugin</span><span style="color:#E1E4E8">(file_path, file_type</span><span style="color:#F97583">=</span><span style="color:#9ECBFF">'image'</span><span style="color:#E1E4E8">):</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">    """</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">    为插件提供的文件上传函数</span></span></span>
<span class="line"><span class="line"><span style="color:#9ECBFF">    """</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">    filename </span><span style="color:#F97583">=</span><span style="color:#E1E4E8"> os.path.basename(file_path)</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    if</span><span style="color:#E1E4E8"> allowed_file(filename):</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        dest_dir </span><span style="color:#F97583">=</span><span style="color:#E1E4E8"> os.path.join(</span><span style="color:#79B8FF">DATA_DIR</span><span style="color:#E1E4E8">, file_type)</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        os.makedirs(dest_dir, </span><span style="color:#FFAB70">exist_ok</span><span style="color:#F97583">=</span><span style="color:#79B8FF">True</span><span style="color:#E1E4E8">)</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        dest_path </span><span style="color:#F97583">=</span><span style="color:#E1E4E8"> os.path.join(dest_dir, filename)</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        os.rename(file_path, dest_path)</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        </span></span></span>
<span class="line"><span class="line"><span style="color:#6A737D">        # 调用插件的on_file_upload方法</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        upload_result </span><span style="color:#F97583">=</span><span style="color:#F97583"> await</span><span style="color:#E1E4E8"> plugin_manager.call_on_file_upload(dest_path)</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        </span></span></span>
<span class="line"><span class="line"><span style="color:#6A737D">        # 如果插件返回了自定义的URL，使用插件返回的URL</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        if</span><span style="color:#E1E4E8"> upload_result </span><span style="color:#F97583">and</span><span style="color:#79B8FF"> isinstance</span><span style="color:#E1E4E8">(upload_result, </span><span style="color:#79B8FF">str</span><span style="color:#E1E4E8">):</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">            return</span><span style="color:#E1E4E8"> upload_result</span></span></span>
<span class="line"><span class="line"><span style="color:#E1E4E8">        </span></span></span>
<span class="line"><span class="line"><span style="color:#6A737D">        # 否则使用默认的URL</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#F97583"> f</span><span style="color:#9ECBFF">'http://localhost:4321/data/</span><span style="color:#79B8FF">{</span><span style="color:#E1E4E8">file_type</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF">/</span><span style="color:#79B8FF">{</span><span style="color:#E1E4E8">filename</span><span style="color:#79B8FF">}</span><span style="color:#9ECBFF">'</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">    else</span><span style="color:#E1E4E8">:</span></span></span>
<span class="line"><span class="line"><span style="color:#F97583">        return</span><span style="color:#79B8FF"> None</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


